version: '3'

services:
  number-generator:
    build:
      context: ./app/generator
      dockerfile: Dockerfile.generator
    volumes:
      - numbers-volume:/app

  number-sorter:
    build:
      context: ./app/sorter
      dockerfile: Dockerfile.sorter
    volumes:
      - numbers-volume:/app
    depends_on:
      - number-generator

volumes:
  numbers-volume:
