apiVersion: v1
kind: Pod
metadata:
  name: hpl-pod
spec:
  containers:
    - name: hpl-container
      image: your_repo_name/new_hpl_docker_image
      resources:
        limits:
          memory: 100Mi
          cpu: 100m
        requests:
          memory: 100Mi
          cpu: 100m
      command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
